server:
  port: 20002
  enable-self-preservation: false
  peer-eureka-nodes-update-interval-ms: 600
eureka:
  instance:
    hostname: server2
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://server1:20001/eureka/