server:
  port: 20001
eureka:
  instance:
    hostname: server1
  client:
    service-url:
      defaultZone: http://server1:20001/eureka/
    fetch-registry: false
    register-with-eureka: false
  server:
    enable-self-preservation: false
