spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KouLouYiMaSi/springcloud
          search-paths: config-repo
          username: KouLouYiMaSi
          password: huo1598100
server:
  port: 7001